### ISSUE TITLE
OpenCL error Error: [ComputeCpp:RT0208] Failed to enqueue OpenCL command  (clEnqueueNDRangeKernel) CL_OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by JulyJohn** [lukeiwanski/tensorflow#172]
------------------------

### System information
- **Have I written custom code**: No
- **OS Platform and Distribution**:Linux Ubuntu 16.04
- **TensorFlow installed from**: build from the source with https://github.com/lukeiwanski/tensorflow/tree/dev/eigen_mehdi
- **TensorFlow version**:v1.1.0-rc1-7178-g9586bef 1.3.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:0.5.4
- **CUDA/cuDNN version**: none
- **GPU model and memory**: none
- **Exact command to reproduce**:~/Downloads/models/tutorials/image/imagenet$ python3 classify_image.py

### Describe the problem
I have an i5-6500 CPU but no GPU in my computer.
i tried the "hello world" example, it was OK.
But, when i try the imagenet example from http://github.com/tensorflow/models, I got a erro like this:

```
OpenCL error Error: [ComputeCpp:RT0208] Failed to enqueue OpenCL command  (clEnqueueNDRangeKernel) CL_OUT_OF_RESOURCES
```

after that I tried the mnist example, and I got this problem too.

### Source code / logs
```

2017-10-31 20:57:41.791291: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-10-31 20:57:41.794652: W ./tensorflow/core/common_runtime/sycl/sycl_device.h:49] No OpenCL GPU found that is supported by ComputeCpp, trying OpenCL CPU
2017-10-31 20:57:41.872196: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:66] Found following OpenCL devices:
2017-10-31 20:57:41.872229: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:68] id: 0, type: CPU, name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz, vendor: Intel(R) Corporation, profile: FULL_PROFILE
2017-10-31 20:57:42.252877: W ./tensorflow/core/framework/op_def_util.cc:334] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
 OpenCL error Error: [ComputeCpp:RT0208] Failed to enqueue OpenCL command  (clEnqueueNDRangeKernel) CL_OUT_OF_RESOURCES 
Error detected Inside Sycl Device.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Unknown error detected on device /job:localhost/replica:0/task:0/device:SYCL:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_image.py", line 227, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "classify_image.py", line 193, in main
    run_inference_on_image(image)
  File "classify_image.py", line 157, in run_inference_on_image
    {'DecodeJpeg/contents:0': image_data})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unknown error detected on device /job:localhost/replica:0/task:0/device:SYCL:0
```

clinfo
```
Number of platforms                               1
  Platform Name                                   Intel(R) OpenCL
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 2.0 
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_fp64 cl_khr_image2d_from_buffer
  Platform Extensions function suffix             INTEL

  Platform Name                                   Intel(R) OpenCL
Number of devices                                 1
  Device Name                                     Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0 (Build 475)
  Driver Version                                  1.2.0.475
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               4
  Max clock frequency                             3200MHz
  Device Partition                                (core)
    Max number of sub-devices                     4
    Supported partition types                     by counts, equally, by names (Intel)
  Max work item dimensions                        3
  Max work item sizes                             8192x8192x8192
  Max work group size                             8192
  Preferred work group size multiple              128
  Preferred / native vector sizes                 
    char                                                 1 / 32      
    short                                                1 / 16      
    int                                                  1 / 8       
    long                                                 1 / 4       
    half                                                 0 / 0        (n/a)
    float                                                1 / 8       
    double                                               1 / 4        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              8284872704 (7.716GiB)
  Error Correction support                        No
  Max memory allocation                           2071218176 (1.929GiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   Yes
    Fine-grained system sharing                   Yes
    Atomics                                       Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics                 
    SVM                                           64 bytes
    Global                                        64 bytes
    Local                                         0 bytes
  Max size for global variable                    65536 (64KiB)
  Preferred total size of global vars             65536 (64KiB)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        262144
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             480
    Max size for 1D images from buffer            129451136 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   64 bytes
    Pitch alignment for 2D image buffers          64 bytes
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 480
    Max number of write image args                480
    Max number of read/write image args           480
  Max number of pipe args                         16
  Max active pipe reservations                    65535
  Max pipe packet size                            1024
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        131072 (128KiB)
  Max number of constant args                     480
  Max size of kernel argument                     3840 (3.75KiB)
  Queue properties (on host)                      
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Local thread execution (Intel)                Yes
  Queue properties (on device)                    
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                4294967295 (4GiB)
    Max size                                      4294967295 (4GiB)
  Max queues on device                            4294967295
  Max events on device                            4294967295
  Prefer user sync for interop                    No
  Profiling timer resolution                      1ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_fp64 cl_khr_image2d_from_buffer 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [INTEL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

```

**Comment by DuncanMcBain** [comment]
Hi @JulyJohn, thanks for your report. As described on this page, https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html, CL_OUT_OF_RESOURCES is returned from the OpenCL implementation "if there is a failure to queue the execution instance of kernel on the command-queue because of insufficient resources needed to execute the kernel. For example, the explicitly specified local_work_size causes a failure to execute the kernel because of insufficient resources such as registers or local memory." I guess one of the kernels in Tensorflow uses too many resources for Intel CPU? I'm not sure, however. I'll find out from our developers if there's a way we can print some more information about exactly what is failing (and therefore *why* it is failing).

**Comment by JulyJohn** [comment]
@DuncanMcBain thanks for your reply:-)
I was wondering what the meaning of different branches are, and the difference between them.
Since I only compiled successfully with "eigen_mehdi" branch, but always failed with almost of the other branches. 
And shall I use the "intel_gpu" branch to compile? But I can't compile it successfully. When the compile process is coming to an end(maybe like 3900/4200), it throw an error like this:

```
ERROR: /home/john/Downloads/intel-gpu/tensorflow/tensorflow/core/kernels/BUILD:2781:1: C++ compilation of rule '//tensorflow/core/kernels:xent_op' failed (Exit 1)
In file included from tensorflow/core/kernels/xent_op.cc:20:
In file included from ./tensorflow/core/kernels/xent_op.h:20:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14:
In file included from external/eigen_archive/Eigen/Core:299:
In file included from external/local_config_sycl/crosstool/../sycl/include/SYCL/sycl.hpp:20:
In file included from external/local_config_sycl/crosstool/../sycl/include/SYCL/sycl_interface.h:54:
external/local_config_sycl/crosstool/../sycl/include/SYCL/multi_pointer.h:342:3: error: multiple overloads of 'global_ptr' instantiate to the same signature 'void (pointer_t)' (aka 'void (__attribute__((address_space(1))) float *)')
  global_ptr(pointer_t ptr) : Base(ptr) {}
  ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclExprConstructor.h:42:74: note: in instantiation of template class 'cl::sycl::global_ptr<__attribute__((address_space(1))) float>' requested here
  EvalToLHSConstructor(const utility::tuple::Tuple<Params...> &t) : expr(ConvertToActualTypeSycl(typename Eigen::internal::remove_all<PtrType>::type, utility::tuple::get<N>(t))) {}
                                                                         ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h:50:88: note: expanded from macro 'ConvertToActualTypeSycl'
  #define ConvertToActualTypeSycl(Scalar, buf_acc) reinterpret_cast<typename cl::sycl::global_ptr<Scalar>::pointer_t>((&(*buf_acc.get_pointer())))
                                                                                       ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclExprConstructor.h:226:1: note: in instantiation of member function 'Eigen::TensorSycl::internal::EvalToLHSConstructor<__attribute__((address_space(1))) float *, 0, cl::sycl::accessor<unsigned char, 1, cl::sycl::access::mode::write, cl::sycl::access::target::global_buffer, cl::sycl::codeplay::access::placeholder::false_t>, cl::sycl::accessor<unsigned char, 1, cl::sycl::access::mode::read, cl::sycl::access::target::global_buffer, cl::sycl::codeplay::access::placeholder::false_t> >::EvalToLHSConstructor' requested here
EVALTO(const)
^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclExprConstructor.h:223:41: note: expanded from macro 'EVALTO'
  : nestedExpression(funcD.xprExpr, t), buffer(t), expr(buffer.expr, nestedExpression.expr) {}\
                                        ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclExprConstructor.h:505:10: note: in instantiation of function template specialization 'Eigen::TensorSycl::internal::ExprConstructor<const Eigen::TensorEvalToOp<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakeGlobalPointer> >, MakeGlobalPointer>, const Eigen::TensorEvalToOp<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::TensorSycl::internal::PlaceHolder<const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakePointer>, 1> >, MakePointer>, cl::sycl::accessor<unsigned char, 1, cl::sycl::access::mode::write, cl::sycl::access::target::global_buffer, cl::sycl::codeplay::access::placeholder::false_t>, cl::sycl::accessor<unsigned char, 1, cl::sycl::access::mode::read, cl::sycl::access::target::global_buffer, cl::sycl::codeplay::access::placeholder::false_t> >::ExprConstructor<Eigen::TensorSycl::internal::FunctorExtractor<Eigen::TensorEvaluator<const Eigen::TensorEvalToOp<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakePointer> >, MakePointer>, const Eigen::SyclDevice> > >' requested here
  return ExprConstructor<OrigExpr, IndexExpr, Params...>(funcD, t);
         ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclRun.h:39:33: note: in instantiation of function template specialization 'Eigen::TensorSycl::internal::createDeviceExpression<const Eigen::TensorEvalToOp<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakeGlobalPointer> >, MakeGlobalPointer>, const Eigen::TensorEvalToOp<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::TensorSycl::internal::PlaceHolder<const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakePointer>, 1> >, MakePointer>, Eigen::TensorSycl::internal::FunctorExtractor<Eigen::TensorEvaluator<const Eigen::TensorEvalToOp<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakePointer> >, MakePointer>, const Eigen::SyclDevice> >, cl::sycl::accessor<unsigned char, 1, cl::sycl::access::mode::write, cl::sycl::access::target::global_buffer, cl::sycl::codeplay::access::placeholder::false_t>, cl::sycl::accessor<unsigned char, 1, cl::sycl::access::mode::read, cl::sycl::access::target::global_buffer, cl::sycl::codeplay::access::placeholder::false_t> >' requested here
    auto device_expr =internal::createDeviceExpression<DevExpr, PlaceHolderExpr>(functors, tuple_of_accessors);
                                ^
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorSyclRun.h:37:3: note: in instantiation of member function 'Eigen::TensorSycl::ExecExprFunctorKernel<const Eigen::TensorEvalToOp<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakePointer> >, MakePointer>, Eigen::TensorSycl::internal::FunctorExtractor<Eigen::TensorEvaluator<const Eigen::TensorEvalToOp<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakePointer> >, MakePointer>, const Eigen::SyclDevice> >, utility::tuple::Tuple<cl::sycl::accessor<unsigned char, 1, cl::sycl::access::mode::write, cl::sycl::access::target::global_buffer, cl::sycl::codeplay::access::placeholder::false_t>, cl::sycl::accessor<unsigned char, 1, cl::sycl::access::mode::read, cl::sycl::access::target::global_buffer, cl::sycl::codeplay::access::placeholder::false_t> > >::operator()' requested here
  void operator()(cl::sycl::nd_item<1> itemID) {
  ^
external/local_config_sycl/crosstool/../sycl/include/SYCL/apis.h:982:5: note: (skipping 16 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    kernelgen_parallel_for_nd<
    ^
./tensorflow/core/kernels/xent_op.h:102:20: note: in instantiation of function template specialization 'Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, MakePointer>, Eigen::SyclDevice>::operator=<Eigen::TensorReductionOp<Eigen::internal::SumReducer<float>, const Eigen::IndexList<Eigen::type2index<1>>, const Eigen::TensorForcedEvalOp<const Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_product_op<const float, const float>, const Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long>, 16, MakePointer>, const Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::TensorBroadcastingOp<const Eigen::IndexList<Eigen::type2index<1>, int>, const Eigen::TensorForcedEvalOp<const Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakePointer> > > >, const Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long>, 16, MakePointer> > > >, MakePointer> >' requested here
    loss.device(d) =
                   ^
tensorflow/core/kernels/xent_op.cc:87:31: note: in instantiation of member function 'tensorflow::functor::XentEigenImpl<Eigen::SyclDevice, float>::Compute' requested here
    XentEigenImpl<Device, T>::Compute(d, logits, labels, scratch, loss,
                              ^
tensorflow/core/kernels/xent_op.cc:71:5: note: in instantiation of member function 'tensorflow::functor::XentFunctorBase<Eigen::SyclDevice, float>::operator()' requested here
    functor(context->eigen_device<Device>(), logits_in.matrix<T>(),
    ^
tensorflow/core/kernels/xent_op.cc:38:12: note: in instantiation of member function 'tensorflow::SoftmaxXentWithLogitsOp<Eigen::SyclDevice, float>::Compute' requested here
  explicit SoftmaxXentWithLogitsOp(OpKernelConstruction* context)
           ^
tensorflow/core/kernels/xent_op.cc:129:25: note: in instantiation of member function 'tensorflow::SoftmaxXentWithLogitsOp<Eigen::SyclDevice, float>::SoftmaxXentWithLogitsOp' requested here
                        SoftmaxXentWithLogitsOp<SYCLDevice, float>);
                        ^
external/local_config_sycl/crosstool/../sycl/include/SYCL/multi_pointer.h:334:3: note: previous declaration is here
  global_ptr(dataType *ptr);
  ^
1 error generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1718.864s, Critical Path: 79.28s
FAILED: Build did NOT complete successfully
```

**Comment by DuncanMcBain** [comment]
Hi,
/dev/eigen_mehdi is the branch you should use, it refers to a particular version of Eigen that we pull from. The Intel GPU branch is likely to be a little stale at the moment, we investigated it a little but I don't think anyone's working on it right now.

**Comment by lukeiwanski** [comment]
@JulyJohn Apologies for so many branches.. cleaning that is high on my priority list. There are few reasons for that.. for instance what @DuncanMcBain mentioned above - we are actively improving Eigen library that drives TensorFlow computation. 
As well branches are created for: pull requests and different features (across different platforms) that we are working on

We did work on Intel GPU support via Beignet - however that has been put on hold for now, therefore branch is quite behind.
As Duncan suggested use dev/eigen_mehdi or dev/amd_gpu 

Back to your compilation problem: it seems that you are using old version of ComputeCpp could you pick up the latest and give it a spin?

Luke

**Comment by JulyJohn** [comment]
Hi, @DuncanMcBain @lukeiwanski 
I tried it again, and got an erro like this:

```
hejunhua@hejunhua-B150M-D3H:~/Downloads/code/models/tutorials/image/imagenet$ python3 classify_image.py 
>> Downloading inception-2015-12-05.tgz 100.0%
Successfully downloaded inception-2015-12-05.tgz 88931400 bytes.
2017-11-21 11:54:10.564309: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-11-21 11:54:10.610305: W ./tensorflow/core/common_runtime/sycl/sycl_device.h:49] No OpenCL GPU found that is supported by ComputeCpp, trying OpenCL CPU
2017-11-21 11:54:10.657781: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:66] Found following OpenCL devices:
2017-11-21 11:54:10.657843: I ./tensorflow/core/common_runtime/sycl/sycl_device.h:68] id: 0, type: CPU, name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz, vendor: Intel(R) Corporation, profile: FULL_PROFILE
2017-11-21 11:54:10.988000: W ./tensorflow/core/framework/op_def_util.cc:334] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
LLVM ERROR: Cannot select: 0x7f9dfc6bf560: v2i64 = bitcast 0x7f9dfdcb7380 [ORD=25] [ID=136]
  0x7f9dfdcb7380: v4i64 = and 0x7f9dfc100db0, 0x7f9dfdcb6c10 [ORD=16] [ID=131]
    0x7f9dfc100db0: v4i64 = bitcast 0x7f9dfdd66710 [ORD=16] [ID=126]
      0x7f9dfdd66710: v8i32 = X86ISD::VSHLI 0x7f9dfdd66e80, 0x7f9dfdd675f0 [ORD=13] [ID=124]
        0x7f9dfdd66e80: v8i32 = X86ISD::VZEXT 0x7f9dfc52bcb0 [ORD=12] [ID=123]
          0x7f9dfc52bcb0: v8i16 = X86ISD::PINSRW 0x7f9dfc0c5640, 0x7f9dfc6bf450, 0x7f9dfc100310 [ORD=11] [ID=122]
            0x7f9dfc0c5640: v8i16 = X86ISD::PINSRW 0x7f9dfc63eab0, 0x7f9dfdcb6b00, 0x7f9dfd221680 [ORD=11] [ID=121]
              0x7f9dfc63eab0: v8i16 = X86ISD::PINSRW 0x7f9dfdcb6e30, 0x7f9dfc0fffe0, 0x7f9dfc50d250 [ORD=11] [ID=120]
                0x7f9dfdcb6e30: v8i16 = X86ISD::PINSRW 0x7f9dfc6bf780, 0x7f9dfc100420, 0x7f9dfc100200 [ORD=11] [ID=118]
                  0x7f9dfc6bf780: v8i16 = X86ISD::PINSRW 0x7f9dfc0c5200, 0x7f9dfc50d9c0, 0x7f9dfdcb7050 [ORD=11] [ID=116]



                  0x7f9dfc100420: i32 = any_extend 0x7f9dfc2f11f0 [ORD=11] [ID=72]

                  0x7f9dfc100200: i64 = Constant<4> [ID=25]
                0x7f9dfc0fffe0: i32 = any_extend 0x7f9dfce63d70 [ORD=11] [ID=73]
                  0x7f9dfce63d70: i16,ch = CopyFromReg 0x7f9dfd623b30, 0x7f9dfe028c40 [ORD=9] [ID=50]

                0x7f9dfc50d250: i64 = Constant<5> [ID=26]
              0x7f9dfdcb6b00: i32 = any_extend 0x7f9dfcc676c0 [ORD=11] [ID=74]
                0x7f9dfcc676c0: i16,ch = CopyFromReg 0x7f9dfd623b30, 0x7f9dfc52bba0 [ORD=10] [ID=51]
                  0x7f9dfc52bba0: i16 = Register %vreg210 [ID=10]
              0x7f9dfd221680: i64 = Constant<6> [ID=27]
            0x7f9dfc6bf450: i32 = any_extend 0x7f9dfc50dad0 [ORD=11] [ID=75]
              0x7f9dfc50dad0: i16,ch = CopyFromReg 0x7f9dfd623b30, 0x7f9dfc63e890 [ORD=11] [ID=52]
                0x7f9dfc63e890: i16 = Register %vreg211 [ID=11]
            0x7f9dfc100310: i64 = Constant<7> [ID=28]
        0x7f9dfdd675f0: i8 = Constant<13> [ID=17]
    0x7f9dfdcb6c10: v4i64 = bitcast 0x7f9dfd976a90 [ORD=16] [ID=108]
      0x7f9dfd976a90: v8i32 = X86ISD::VBROADCAST 0x7f9dfc2f10e0 [ID=99]
        0x7f9dfc2f10e0: i32,ch = load 0x7f9dfd623b30, 0x7f9dfccba180, 0x7f9dfce63820<LD4[ConstantPool]> [ID=86]
          0x7f9dfccba180: i64 = X86ISD::Wrapper 0x7f9dfc2f0640 [ID=63]
            0x7f9dfc2f0640: i64 = TargetConstantPool<i32 268435455> 0 [ID=39]
          0x7f9dfce63820: i64 = undef [ID=29]
In function: SYCL_ef04060d33f36a4172a9c5f3b83552c7_0
 SYCL Runtime closed with the following errors:
SYCL objects are still alive while the runtime is shutting down

 This probably indicates that a SYCL object was created  but not properly destroyed. 
terminate called without an active exception
Stack dump:
0.	Running pass 'Function Pass Manager' on module 'main'.
1.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@SYCL_ef04060d33f36a4172a9c5f3b83552c7_0'
Aborted (core dumped)
```

**Comment by lukeiwanski** [comment]
Hey @JulyJohn 

Sorry about the late reply - holidays sesson can be hectic. Can you confirm that this issue is still happening on 3e999990f1b69f3c7cd87dc80eb9de48aa61d9b1 with ComputeCpp 0.5.0 ?

If so, @DuncanMcBain could you take a look?

**Comment by lukeiwanski** [comment]
@JulyJohn  / @DuncanMcBain  ping

**Comment by DuncanMcBain** [comment]
0.5.0 isn't the most recent version any more, so it would be interesting to see if we can replicate it on the newest version.
